-- ============================================================
-- FEATURE: Opening Cash in Hand
-- ------------------------------------------------------------
-- Records the company's initial cash position when it starts
-- using the system, mirroring the existing party opening-balance
-- mechanism (see trg_party_opening_balance).
--
-- Double-entry posted (same convention as party opening balances):
--     DEBIT  Cash (Asset)            <amount>
--     CREDIT Owner's Capital (Equity)<amount>
--
-- The Cash balance shown by the app comes from vw_trial_balance
-- (account 'Cash'); posting the entry above makes opening cash
-- flow into the dashboard / cash ledger automatically, with no
-- change to any existing object or calculation.
--
-- Idempotent & editable: a single company-level row is kept; the
-- setter UPSERTs it and keeps the linked journal entry in sync, so
-- re-saving never double-counts.
-- ============================================================

-- ---------- Table -------------------------------------------------
CREATE TABLE IF NOT EXISTS public.opening_cash (
    opening_cash_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    entry_date      DATE          NOT NULL DEFAULT CURRENT_DATE,
    journal_id      BIGINT,
    created_by_id   INTEGER,
    date_created    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_singleton    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT opening_cash_amount_nonneg  CHECK (amount >= 0),
    CONSTRAINT opening_cash_singleton_chk  CHECK (is_singleton = TRUE),
    CONSTRAINT opening_cash_singleton_uniq UNIQUE (is_singleton),
    CONSTRAINT opening_cash_journal_fk FOREIGN KEY (journal_id)
        REFERENCES public.journalentries (journal_id),
    CONSTRAINT opening_cash_user_fk FOREIGN KEY (created_by_id)
        REFERENCES public.auth_user (id)
);

ALTER TABLE public.opening_cash OWNER TO postgres;

COMMENT ON TABLE public.opening_cash IS
    'Company opening cash-in-hand. Single row; setter keeps the linked Opening Cash journal entry in sync.';

-- ---------- Getter ------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_opening_cash_json()
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
    result jsonb;
BEGIN
    SELECT jsonb_build_object(
               'amount',     oc.amount,
               'entry_date', oc.entry_date,
               'journal_id', oc.journal_id,
               'is_set',     TRUE
           )
    INTO result
    FROM public.opening_cash oc
    WHERE oc.is_singleton
    LIMIT 1;

    IF result IS NULL THEN
        result := jsonb_build_object(
                      'amount', 0, 'entry_date', NULL,
                      'journal_id', NULL, 'is_set', FALSE);
    END IF;

    RETURN result;
END;
$$;

ALTER FUNCTION public.get_opening_cash_json() OWNER TO postgres;

-- ---------- Setter (UPSERT + balanced journal posting) ------------
CREATE OR REPLACE FUNCTION public.set_opening_cash_from_json(data jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
    v_amount   NUMERIC := ROUND(COALESCE((data->>'amount')::NUMERIC, 0), 2);
    v_user     INTEGER := NULLIF(data->>'created_by_id', '')::INTEGER;
    v_cash_acc BIGINT;
    v_cap_acc  BIGINT;
    v_row      public.opening_cash%ROWTYPE;
    j_id       BIGINT;
BEGIN
    IF v_amount < 0 THEN
        RAISE EXCEPTION 'Opening cash cannot be negative';
    END IF;

    SELECT account_id INTO v_cash_acc
    FROM public.chartofaccounts
    WHERE account_name = 'Cash' AND account_type = 'Asset'
    LIMIT 1;

    SELECT account_id INTO v_cap_acc
    FROM public.chartofaccounts
    WHERE account_name = 'Owner''s Capital'
    LIMIT 1;

    IF v_cash_acc IS NULL THEN
        RAISE EXCEPTION 'Cash account not found in ChartOfAccounts';
    END IF;
    IF v_cap_acc IS NULL THEN
        RAISE EXCEPTION 'Owner''s Capital account not found in ChartOfAccounts';
    END IF;

    SELECT * INTO v_row
    FROM public.opening_cash
    WHERE is_singleton
    LIMIT 1;

    -- Helper journal id (existing one if present)
    j_id := v_row.journal_id;

    IF v_amount > 0 THEN
        IF j_id IS NULL THEN
            -- create a fresh balanced entry
            INSERT INTO public.journalentries (entry_date, description)
            VALUES (CURRENT_DATE, 'Opening Cash in Hand')
            RETURNING journal_id INTO j_id;

            INSERT INTO public.journallines (journal_id, account_id, debit)
            VALUES (j_id, v_cash_acc, v_amount);

            INSERT INTO public.journallines (journal_id, account_id, credit)
            VALUES (j_id, v_cap_acc, v_amount);
        ELSE
            -- keep the existing entry, just update the two amounts
            UPDATE public.journallines
               SET debit = v_amount, credit = NULL
             WHERE journal_id = j_id AND account_id = v_cash_acc;

            UPDATE public.journallines
               SET credit = v_amount, debit = NULL
             WHERE journal_id = j_id AND account_id = v_cap_acc;
        END IF;
    ELSE
        -- amount == 0: remove any previously posted entry so nothing lingers.
        -- Clear the FK reference first so the entry can be deleted safely.
        IF j_id IS NOT NULL THEN
            UPDATE public.opening_cash SET journal_id = NULL WHERE journal_id = j_id;
            DELETE FROM public.journallines   WHERE journal_id = j_id;
            DELETE FROM public.journalentries WHERE journal_id = j_id;
            j_id := NULL;
        END IF;
    END IF;

    IF v_row.opening_cash_id IS NULL THEN
        INSERT INTO public.opening_cash (amount, entry_date, journal_id, created_by_id)
        VALUES (v_amount, CURRENT_DATE, j_id, v_user);
    ELSE
        UPDATE public.opening_cash
           SET amount        = v_amount,
               journal_id    = j_id,
               created_by_id = COALESCE(v_user, created_by_id),
               date_updated  = CURRENT_TIMESTAMP
         WHERE opening_cash_id = v_row.opening_cash_id;
    END IF;

    RETURN public.get_opening_cash_json();
END;
$$;

ALTER FUNCTION public.set_opening_cash_from_json(jsonb) OWNER TO postgres;



-- ============================================================
-- Seed: Core Chart of Accounts (system-required foundation)
-- ------------------------------------------------------------
-- The accounting layer (cash balance, trial balance, party
-- opening balances, ledgers, sales/purchase posting, and the
-- Opening Cash feature) all reference these accounts BY NAME.
-- On a fresh database `chartofaccounts` is empty, so these must
-- exist before any accounting action can post.
--
-- These 8 accounts mirror production's core accounts. Expense
-- accounts (EXP-xxxx) are NOT seeded here — they are created
-- automatically when Expense parties are added.
--
-- Idempotent: each account is inserted only if an account with
-- the same (case-insensitive, trimmed) name does not already
-- exist, so it is safe to run more than once.
-- ============================================================

INSERT INTO public.chartofaccounts (account_code, account_name, account_type)
SELECT v.code, v.name, v.type
FROM (VALUES
    ('1000', 'Cash',                'Asset'),
    ('1200', 'Accounts Receivable', 'Asset'),
    ('1400', 'Inventory',           'Asset'),
    ('2000', 'Accounts Payable',    'Liability'),
    ('3000', 'Owner''s Capital',    'Equity'),
    ('3001', 'Opening Balance',     'Equity'),
    ('4000', 'Sales Revenue',       'Revenue'),
    ('5000', 'Cost of Goods Sold',  'Expense')
) AS v(code, name, type)
WHERE NOT EXISTS (
    SELECT 1 FROM public.chartofaccounts c
    WHERE TRIM(LOWER(c.account_name)) = TRIM(LOWER(v.name))
);

-- Show the result
SELECT account_id, account_code, account_name, account_type
FROM public.chartofaccounts
ORDER BY account_id;
