-- ============================================================
-- FEATURE: Month-End Close (profit recognition into Retained Earnings)
-- ------------------------------------------------------------
-- Closing a month moves that month's EARNED profit
-- (Sales Revenue - Cost of Goods Sold - Expenses) out of the
-- temporary income/expense accounts and into Retained Earnings,
-- and records it in a month-by-month log.
--
-- Closing entry (dated last day of month, NO cash), e.g. for a
-- month with Sales 60,000 and COGS 50,000:
--     DEBIT  Sales Revenue       60,000   (empties it)
--     CREDIT Cost of Goods Sold  50,000   (empties it)
--     CREDIT Retained Earnings   10,000   (earned profit lands here)
--
-- Rules: one close per month (UNIQUE); period-scoped so order does
-- not matter; reversible; closing entries are tagged
-- ('Month-End Close YYYY-MM') and excluded from profit math so they
-- never double-count. Net Position (Assets - Liabilities) is
-- unchanged by a close. All tables are raw SQL / unmanaged by Django.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.period_closes (
    close_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_year     INTEGER       NOT NULL,
    period_month    INTEGER       NOT NULL,
    profit_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
    sales_amount    NUMERIC(14,2) NOT NULL DEFAULT 0,
    cogs_amount     NUMERIC(14,2) NOT NULL DEFAULT 0,
    expenses_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    journal_id      BIGINT,
    closed_by_id    INTEGER,
    closed_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT period_month_chk  CHECK (period_month BETWEEN 1 AND 12),
    CONSTRAINT period_unique     UNIQUE (period_year, period_month),
    CONSTRAINT period_journal_fk FOREIGN KEY (journal_id)
        REFERENCES public.journalentries (journal_id),
    CONSTRAINT period_user_fk    FOREIGN KEY (closed_by_id)
        REFERENCES public.auth_user (id)
);

COMMENT ON TABLE public.period_closes IS
    'Month-end profit recognitions into Retained Earnings (one row per closed month).';


-- ---------- Preview a month's earned-profit breakdown (no posting) ----------
CREATE OR REPLACE FUNCTION public.preview_period_close(p_year integer, p_month integer)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_start  date;
    v_end    date;
    v_sales  numeric(14,2) := 0;
    v_cogs   numeric(14,2) := 0;
    v_exp    numeric(14,2) := 0;
    v_closed boolean := FALSE;
BEGIN
    IF p_month NOT BETWEEN 1 AND 12 THEN
        RAISE EXCEPTION 'month must be between 1 and 12';
    END IF;
    v_start := make_date(p_year, p_month, 1);
    v_end   := (v_start + INTERVAL '1 month' - INTERVAL '1 day')::date;

    SELECT
        COALESCE(SUM(CASE WHEN c.account_type = 'Revenue'
                          THEN jl.credit - jl.debit END), 0),
        COALESCE(SUM(CASE WHEN c.account_name ILIKE '%cost of goods%'
                          THEN jl.debit - jl.credit END), 0),
        COALESCE(SUM(CASE WHEN c.account_type = 'Expense'
                           AND c.account_name NOT ILIKE '%cost of goods%'
                          THEN jl.debit - jl.credit END), 0)
    INTO v_sales, v_cogs, v_exp
    FROM   public.journallines   jl
    JOIN   public.journalentries je ON je.journal_id = jl.journal_id
    JOIN   public.chartofaccounts c ON c.account_id  = jl.account_id
    WHERE  je.entry_date BETWEEN v_start AND v_end
      AND  c.account_type IN ('Revenue','Expense')
      AND  je.description NOT ILIKE 'Month-End Close%';

    SELECT TRUE INTO v_closed FROM public.period_closes
    WHERE period_year = p_year AND period_month = p_month;

    RETURN jsonb_build_object(
        'year', p_year, 'month', p_month,
        'sales', v_sales, 'cogs', v_cogs, 'expenses', v_exp,
        'profit', ROUND(v_sales - v_cogs - v_exp, 2),
        'already_closed', COALESCE(v_closed, FALSE)
    );
END;
$function$;


-- ---------- Close a month (posts the balanced closing entry) ----------
CREATE OR REPLACE FUNCTION public.close_period_from_json(p_data jsonb)
RETURNS jsonb
LANGUAGE plpgsql
AS $function$
DECLARE
    v_year   integer := (p_data->>'year')::integer;
    v_month  integer := (p_data->>'month')::integer;
    v_user   integer := NULLIF(p_data->>'created_by_id','')::integer;
    v_start  date;
    v_end    date;
    v_sales  numeric(14,2) := 0;
    v_cogs   numeric(14,2) := 0;
    v_exp    numeric(14,2) := 0;
    v_profit numeric(14,2) := 0;
    v_re     bigint;
    v_journal bigint;
BEGIN
    IF v_month NOT BETWEEN 1 AND 12 THEN
        RAISE EXCEPTION 'month must be between 1 and 12';
    END IF;
    IF EXISTS (SELECT 1 FROM public.period_closes
               WHERE period_year = v_year AND period_month = v_month) THEN
        RAISE EXCEPTION 'Period %-% is already closed', v_year,
                        lpad(v_month::text, 2, '0');
    END IF;

    v_start := make_date(v_year, v_month, 1);
    v_end   := (v_start + INTERVAL '1 month' - INTERVAL '1 day')::date;

    SELECT
        COALESCE(SUM(CASE WHEN c.account_type = 'Revenue'
                          THEN jl.credit - jl.debit END), 0),
        COALESCE(SUM(CASE WHEN c.account_name ILIKE '%cost of goods%'
                          THEN jl.debit - jl.credit END), 0),
        COALESCE(SUM(CASE WHEN c.account_type = 'Expense'
                           AND c.account_name NOT ILIKE '%cost of goods%'
                          THEN jl.debit - jl.credit END), 0)
    INTO v_sales, v_cogs, v_exp
    FROM   public.journallines   jl
    JOIN   public.journalentries je ON je.journal_id = jl.journal_id
    JOIN   public.chartofaccounts c ON c.account_id  = jl.account_id
    WHERE  je.entry_date BETWEEN v_start AND v_end
      AND  c.account_type IN ('Revenue','Expense')
      AND  je.description NOT ILIKE 'Month-End Close%';

    v_profit := ROUND(v_sales - v_cogs - v_exp, 2);

    SELECT account_id INTO v_re
    FROM   public.chartofaccounts
    WHERE  account_name = 'Retained Earnings' AND account_type = 'Equity'
    LIMIT  1;
    IF v_re IS NULL THEN
        RAISE EXCEPTION 'Retained Earnings account not found in ChartOfAccounts';
    END IF;

    INSERT INTO public.journalentries (entry_date, description)
    VALUES (v_end, 'Month-End Close ' || v_year || '-' || lpad(v_month::text, 2, '0'))
    RETURNING journal_id INTO v_journal;

    -- Reverse each nominal account's period activity (zeroes Revenue/Expense for the month)
    INSERT INTO public.journallines (journal_id, account_id, debit, credit)
    SELECT v_journal, t.account_id,
           CASE WHEN t.net_dr < 0 THEN -t.net_dr ELSE NULL END,   -- debit clears net-credit (revenue)
           CASE WHEN t.net_dr > 0 THEN  t.net_dr ELSE NULL END    -- credit clears net-debit (expense)
    FROM (
        SELECT jl.account_id, SUM(jl.debit) - SUM(jl.credit) AS net_dr
        FROM   public.journallines   jl
        JOIN   public.journalentries je ON je.journal_id = jl.journal_id
        JOIN   public.chartofaccounts c ON c.account_id  = jl.account_id
        WHERE  je.entry_date BETWEEN v_start AND v_end
          AND  c.account_type IN ('Revenue','Expense')
          AND  je.description NOT ILIKE 'Month-End Close%'
        GROUP  BY jl.account_id
        HAVING SUM(jl.debit) - SUM(jl.credit) <> 0
    ) t;

    -- Balancing line into Retained Earnings
    IF v_profit > 0 THEN
        INSERT INTO public.journallines (journal_id, account_id, credit)
        VALUES (v_journal, v_re, v_profit);
    ELSIF v_profit < 0 THEN
        INSERT INTO public.journallines (journal_id, account_id, debit)
        VALUES (v_journal, v_re, -v_profit);
    END IF;

    INSERT INTO public.period_closes
        (period_year, period_month, profit_amount, sales_amount,
         cogs_amount, expenses_amount, journal_id, closed_by_id)
    VALUES (v_year, v_month, v_profit, v_sales, v_cogs, v_exp, v_journal, v_user);

    RETURN jsonb_build_object('status','success','year',v_year,'month',v_month,
                              'profit',v_profit,'sales',v_sales,'cogs',v_cogs,
                              'expenses',v_exp,'journal_id',v_journal);
END;
$function$;


-- ---------- List closed + open months, plus Retained Earnings balance ----------
CREATE OR REPLACE FUNCTION public.get_period_closes_json()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_closed jsonb;
    v_open   jsonb;
    v_total  numeric(14,2);
    v_re_bal numeric(14,2);
BEGIN
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
               'year', period_year, 'month', period_month,
               'profit', profit_amount, 'sales', sales_amount,
               'cogs', cogs_amount, 'expenses', expenses_amount,
               'closed_at', closed_at
           ) ORDER BY period_year DESC, period_month DESC), '[]'::jsonb)
    INTO v_closed FROM public.period_closes;

    WITH activity AS (
        SELECT DISTINCT EXTRACT(YEAR FROM je.entry_date)::int  AS yr,
                        EXTRACT(MONTH FROM je.entry_date)::int AS mo
        FROM   public.journallines   jl
        JOIN   public.journalentries je ON je.journal_id = jl.journal_id
        JOIN   public.chartofaccounts c ON c.account_id  = jl.account_id
        WHERE  c.account_type IN ('Revenue','Expense')
          AND  je.description NOT ILIKE 'Month-End Close%'
    )
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
               'year', yr, 'month', mo,
               'profit', (preview_period_close(yr, mo)->>'profit')::numeric
           ) ORDER BY yr DESC, mo DESC), '[]'::jsonb)
    INTO v_open
    FROM activity a
    WHERE NOT EXISTS (SELECT 1 FROM public.period_closes pc
                      WHERE pc.period_year = a.yr AND pc.period_month = a.mo);

    SELECT COALESCE(SUM(profit_amount), 0) INTO v_total FROM public.period_closes;

    SELECT COALESCE(balance, 0) INTO v_re_bal
    FROM public.vw_trial_balance WHERE name = 'Retained Earnings';

    RETURN jsonb_build_object(
        'closed', v_closed,
        'open',   v_open,
        'total_closed_profit', v_total,
        'retained_earnings_balance', ROUND(COALESCE(-v_re_bal, 0), 2)  -- credit-normal -> positive
    );
END;
$function$;


-- ---------- Reverse (un-close) a month ----------
CREATE OR REPLACE FUNCTION public.reverse_period_close(p_year integer, p_month integer)
RETURNS jsonb
LANGUAGE plpgsql
AS $function$
DECLARE
    v_journal bigint;
BEGIN
    SELECT journal_id INTO v_journal FROM public.period_closes
    WHERE period_year = p_year AND period_month = p_month;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('status','error','message','That month is not closed');
    END IF;

    UPDATE public.period_closes SET journal_id = NULL
    WHERE period_year = p_year AND period_month = p_month;
    IF v_journal IS NOT NULL THEN
        DELETE FROM public.journallines   WHERE journal_id = v_journal;
        DELETE FROM public.journalentries WHERE journal_id = v_journal;
    END IF;
    DELETE FROM public.period_closes
    WHERE period_year = p_year AND period_month = p_month;

    RETURN jsonb_build_object('status','success','year',p_year,'month',p_month);
END;
$function$;
