-- ============================================================
-- FEATURE: Contra Entry (party-to-party transfer in one entry)
-- ------------------------------------------------------------
-- Moves a balance directly between two parties without the
-- Cash double-hop. A transfer FROM party A TO party B posts ONE
-- balanced journal entry:
--     DEBIT  B's AP account  (party_id = B)   -- like "pay to B"
--     CREDIT A's AR account  (party_id = A)   -- like "receive from A"
-- Net effect: A's balance goes DOWN, B's balance goes UP, and no
-- Cash is touched -- exactly what a receipt-from-A plus a
-- payment-to-B would net to. Mirrors the Payments/Receipts design
-- (table + AFTER triggers that maintain the journal entry).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.contra_entries (
    contra_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_party_id BIGINT       NOT NULL,           -- credited  (money received from)
    to_party_id   BIGINT       NOT NULL,           -- debited   (money paid to)
    amount        NUMERIC(14,4) NOT NULL,
    contra_date   DATE         NOT NULL DEFAULT CURRENT_DATE,
    method        TEXT         DEFAULT 'Transfer',
    reference_no  TEXT,
    journal_id    BIGINT,
    description   TEXT,
    notes         TEXT,
    created_by    INTEGER,
    date_created  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contra_diff_parties CHECK (from_party_id <> to_party_id),
    CONSTRAINT contra_amount_pos   CHECK (amount > 0),
    CONSTRAINT contra_from_fk    FOREIGN KEY (from_party_id) REFERENCES public.parties (party_id) ON DELETE CASCADE,
    CONSTRAINT contra_to_fk      FOREIGN KEY (to_party_id)   REFERENCES public.parties (party_id) ON DELETE CASCADE,
    CONSTRAINT contra_journal_fk FOREIGN KEY (journal_id)    REFERENCES public.journalentries (journal_id) ON DELETE SET NULL,
    CONSTRAINT contra_user_fk    FOREIGN KEY (created_by)    REFERENCES public.auth_user (id) ON DELETE SET NULL
);

CREATE SEQUENCE IF NOT EXISTS public.contra_ref_seq START 1;

COMMENT ON TABLE public.contra_entries IS
    'Party-to-party transfers (contra). Debit To-party / Credit From-party; no cash.';


-- ---------- Trigger: maintain the journal entry ----------
CREATE OR REPLACE FUNCTION public.trg_contra_journal()
RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
    j_id      BIGINT;
    from_acc  BIGINT;
    to_acc    BIGINT;
    from_name TEXT;
    to_name   TEXT;
    journal_desc TEXT;
BEGIN
    -- DELETE: remove the linked journal
    IF TG_OP = 'DELETE' THEN
        DELETE FROM JournalEntries WHERE journal_id = OLD.journal_id;
        RETURN OLD;
    END IF;

    -- UPDATE: skip if nothing relevant changed, else rebuild
    IF TG_OP = 'UPDATE' THEN
        IF OLD.amount = NEW.amount
           AND OLD.from_party_id = NEW.from_party_id
           AND OLD.to_party_id   = NEW.to_party_id
           AND OLD.description IS NOT DISTINCT FROM NEW.description
           AND OLD.contra_date = NEW.contra_date THEN
            RETURN NEW;
        END IF;
        DELETE FROM JournalEntries WHERE journal_id = OLD.journal_id;
    END IF;

    IF TG_OP IN ('INSERT','UPDATE') THEN
        -- From party -> credit side (AR account, like a receipt)
        SELECT ar_account_id, party_name INTO from_acc, from_name
        FROM Parties WHERE party_id = NEW.from_party_id;
        -- To party -> debit side (AP account, like a payment)
        SELECT ap_account_id, party_name INTO to_acc, to_name
        FROM Parties WHERE party_id = NEW.to_party_id;

        IF from_acc IS NULL THEN
            RAISE EXCEPTION 'No AR account found for party %', NEW.from_party_id;
        END IF;
        IF to_acc IS NULL THEN
            RAISE EXCEPTION 'No AP account found for party %', NEW.to_party_id;
        END IF;

        journal_desc := COALESCE(
            NEW.description,
            'Contra: ' || from_name || ' -> ' || to_name ||
            CASE WHEN NEW.reference_no IS NOT NULL AND NEW.reference_no <> ''
                 THEN ' (Ref: ' || NEW.reference_no || ')' ELSE '' END
        );

        INSERT INTO JournalEntries(entry_date, description)
        VALUES (NEW.contra_date, journal_desc)
        RETURNING journal_id INTO j_id;

        -- link back without re-firing this trigger
        PERFORM pg_catalog.set_config('session_replication_role', 'replica', true);
        UPDATE contra_entries SET journal_id = j_id WHERE contra_id = NEW.contra_id;
        PERFORM pg_catalog.set_config('session_replication_role', 'origin', true);

        -- Debit To-party (AP)
        INSERT INTO JournalLines(journal_id, account_id, party_id, debit)
        VALUES (j_id, to_acc, NEW.to_party_id, NEW.amount);
        -- Credit From-party (AR)
        INSERT INTO JournalLines(journal_id, account_id, party_id, credit)
        VALUES (j_id, from_acc, NEW.from_party_id, NEW.amount);
    END IF;

    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_contra_insert ON public.contra_entries;
DROP TRIGGER IF EXISTS trg_contra_update ON public.contra_entries;
DROP TRIGGER IF EXISTS trg_contra_delete ON public.contra_entries;
CREATE TRIGGER trg_contra_insert AFTER INSERT ON public.contra_entries FOR EACH ROW EXECUTE FUNCTION public.trg_contra_journal();
CREATE TRIGGER trg_contra_update AFTER UPDATE ON public.contra_entries FOR EACH ROW EXECUTE FUNCTION public.trg_contra_journal();
CREATE TRIGGER trg_contra_delete AFTER DELETE ON public.contra_entries FOR EACH ROW EXECUTE FUNCTION public.trg_contra_journal();


-- ---------- Create ----------
CREATE OR REPLACE FUNCTION public.make_contra(p_data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE
    v_from BIGINT; v_to BIGINT;
    v_amount NUMERIC(14,4);
    v_desc TEXT; v_date DATE; v_ref TEXT; v_created_by INTEGER; v_id BIGINT;
BEGIN
    v_amount     := (p_data->>'amount')::NUMERIC;
    v_desc       := p_data->>'description';
    v_date       := NULLIF(p_data->>'contra_date','')::DATE;
    v_ref        := p_data->>'reference_no';
    v_created_by := NULLIF(p_data->>'created_by_id','')::INTEGER;

    IF v_amount IS NULL OR v_amount <= 0 THEN
        RAISE EXCEPTION 'Invalid amount: must be > 0';
    END IF;

    SELECT party_id INTO v_from FROM Parties WHERE party_name = p_data->>'from_party_name' LIMIT 1;
    IF v_from IS NULL THEN RAISE EXCEPTION 'From party % not found', p_data->>'from_party_name'; END IF;
    SELECT party_id INTO v_to   FROM Parties WHERE party_name = p_data->>'to_party_name'   LIMIT 1;
    IF v_to IS NULL THEN RAISE EXCEPTION 'To party % not found', p_data->>'to_party_name'; END IF;
    IF v_from = v_to THEN RAISE EXCEPTION 'From and To party cannot be the same'; END IF;

    IF v_ref IS NULL OR v_ref = '' THEN v_ref := 'CON-' || nextval('contra_ref_seq'); END IF;

    INSERT INTO contra_entries(from_party_id, to_party_id, amount, reference_no,
                               description, contra_date, created_by)
    VALUES (v_from, v_to, v_amount, v_ref, v_desc, COALESCE(v_date, CURRENT_DATE), v_created_by)
    RETURNING contra_id INTO v_id;

    RETURN jsonb_build_object('status','success','message','Contra entry created successfully','contra_id', v_id);
END;
$function$;


-- ---------- Update ----------
CREATE OR REPLACE FUNCTION public.update_contra(p_id bigint, p_data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE
    v_amount NUMERIC(14,4); v_desc TEXT; v_date DATE; v_ref TEXT;
    v_from BIGINT; v_to BIGINT; v_created_by INTEGER; v_updated RECORD;
BEGIN
    v_amount     := NULLIF(p_data->>'amount','')::NUMERIC;
    v_desc       := NULLIF(p_data->>'description','');
    v_date       := NULLIF(p_data->>'contra_date','')::DATE;
    v_ref        := NULLIF(p_data->>'reference_no','');
    v_created_by := NULLIF(p_data->>'created_by_id','')::INTEGER;

    IF p_data ? 'from_party_name' THEN
        SELECT party_id INTO v_from FROM Parties WHERE party_name = p_data->>'from_party_name' LIMIT 1;
        IF v_from IS NULL THEN RAISE EXCEPTION 'From party % not found', p_data->>'from_party_name'; END IF;
    END IF;
    IF p_data ? 'to_party_name' THEN
        SELECT party_id INTO v_to FROM Parties WHERE party_name = p_data->>'to_party_name' LIMIT 1;
        IF v_to IS NULL THEN RAISE EXCEPTION 'To party % not found', p_data->>'to_party_name'; END IF;
    END IF;
    IF v_amount IS NOT NULL AND v_amount <= 0 THEN RAISE EXCEPTION 'Invalid amount'; END IF;

    UPDATE contra_entries
    SET amount        = COALESCE(v_amount, amount),
        reference_no  = COALESCE(v_ref, reference_no),
        from_party_id = COALESCE(v_from, from_party_id),
        to_party_id   = COALESCE(v_to, to_party_id),
        description   = COALESCE(v_desc, description),
        contra_date   = COALESCE(v_date, contra_date),
        created_by    = COALESCE(v_created_by, created_by)
    WHERE contra_id = p_id
    RETURNING * INTO v_updated;

    IF NOT FOUND THEN RAISE EXCEPTION 'Contra ID % not found', p_id; END IF;

    RETURN jsonb_build_object('status','success','message','Contra entry updated successfully','contra', to_jsonb(v_updated));
END;
$function$;


-- ---------- Delete ----------
CREATE OR REPLACE FUNCTION public.delete_contra(p_id bigint)
RETURNS jsonb LANGUAGE plpgsql AS $function$
BEGIN
    DELETE FROM contra_entries WHERE contra_id = p_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Contra ID % not found', p_id; END IF;
    RETURN jsonb_build_object('status','success','message','Contra entry deleted successfully');
END;
$function$;


-- ---------- Fetch one / navigate ----------
CREATE OR REPLACE FUNCTION public.get_contra_details(p_id bigint)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE result JSONB;
BEGIN
    SELECT to_jsonb(c)
        || jsonb_build_object('from_party_name', fp.party_name)
        || jsonb_build_object('to_party_name',   tp.party_name)
        || jsonb_build_object('created_by',       COALESCE(u.username, 'N/A'))
    INTO result
    FROM contra_entries c
    LEFT JOIN Parties fp ON fp.party_id = c.from_party_id
    LEFT JOIN Parties tp ON tp.party_id = c.to_party_id
    LEFT JOIN auth_user u ON u.id = c.created_by
    WHERE c.contra_id = p_id;
    RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_previous_contra(p_id bigint)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE result JSONB;
BEGIN
    SELECT to_jsonb(c)
        || jsonb_build_object('from_party_name', fp.party_name)
        || jsonb_build_object('to_party_name',   tp.party_name)
        || jsonb_build_object('created_by',       COALESCE(u.username, 'N/A'))
    INTO result
    FROM contra_entries c
    LEFT JOIN Parties fp ON fp.party_id = c.from_party_id
    LEFT JOIN Parties tp ON tp.party_id = c.to_party_id
    LEFT JOIN auth_user u ON u.id = c.created_by
    WHERE c.contra_id < p_id
    ORDER BY c.contra_id DESC LIMIT 1;
    RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_next_contra(p_id bigint)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE result JSONB;
BEGIN
    SELECT to_jsonb(c)
        || jsonb_build_object('from_party_name', fp.party_name)
        || jsonb_build_object('to_party_name',   tp.party_name)
        || jsonb_build_object('created_by',       COALESCE(u.username, 'N/A'))
    INTO result
    FROM contra_entries c
    LEFT JOIN Parties fp ON fp.party_id = c.from_party_id
    LEFT JOIN Parties tp ON tp.party_id = c.to_party_id
    LEFT JOIN auth_user u ON u.id = c.created_by
    WHERE c.contra_id > p_id
    ORDER BY c.contra_id ASC LIMIT 1;
    RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_last_contra()
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE result JSONB;
BEGIN
    SELECT to_jsonb(c)
        || jsonb_build_object('from_party_name', fp.party_name)
        || jsonb_build_object('to_party_name',   tp.party_name)
        || jsonb_build_object('created_by',       COALESCE(u.username, 'N/A'))
    INTO result
    FROM contra_entries c
    LEFT JOIN Parties fp ON fp.party_id = c.from_party_id
    LEFT JOIN Parties tp ON tp.party_id = c.to_party_id
    LEFT JOIN auth_user u ON u.id = c.created_by
    ORDER BY c.contra_id DESC LIMIT 1;
    RETURN result;
END;
$function$;


-- ---------- Lists ----------
CREATE OR REPLACE FUNCTION public.get_last_20_contras_json(p_data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE result JSONB;
BEGIN
    SELECT jsonb_agg(row_data) INTO result
    FROM (
        SELECT to_jsonb(c)
               || jsonb_build_object('from_party_name', fp.party_name,
                                     'to_party_name',   tp.party_name) AS row_data
        FROM contra_entries c
        JOIN Parties fp ON fp.party_id = c.from_party_id
        JOIN Parties tp ON tp.party_id = c.to_party_id
        ORDER BY c.contra_date DESC, c.contra_id DESC
        LIMIT 20
    ) sub;
    RETURN COALESCE(result, '[]'::jsonb);
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_contras_by_date_json(p_data jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $function$
DECLARE v_start DATE; v_end DATE; result JSONB;
BEGIN
    v_start := (p_data->>'start_date')::DATE;
    v_end   := (p_data->>'end_date')::DATE;
    IF v_start IS NULL OR v_end IS NULL THEN
        RAISE EXCEPTION 'Both start_date and end_date must be provided';
    END IF;

    SELECT jsonb_agg(to_jsonb(c)
               || jsonb_build_object('from_party_name', fp.party_name,
                                     'to_party_name',   tp.party_name)
               ORDER BY c.contra_date DESC, c.contra_id DESC)
    INTO result
    FROM contra_entries c
    JOIN Parties fp ON fp.party_id = c.from_party_id
    JOIN Parties tp ON tp.party_id = c.to_party_id
    WHERE c.contra_date BETWEEN v_start AND v_end;

    RETURN COALESCE(result, '[]'::jsonb);
END;
$function$;
